### ISSUE TITLE
I'm getting segmentation faults on all qt5 apps via this project

### ISSUE THREAD

**Issue by SolarAquarion** [gustawho/appmenu-qt5#1]
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from mpc-qt...Reading symbols from /usr/lib/debug/usr/bin/mpc-qt.debug...(no debugging symbols found)...done.
(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/mpc-qt 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffbd432700 (LWP 21010)]

Thread 1 "mpc-qt" received signal SIGSEGV, Segmentation fault.
0x00007fffb61ba8f4 in ?? () from /usr/lib/libQtGui.so.4
(gdb) bt
#0  0x00007fffb61ba8f4 in  () at /usr/lib/libQtGui.so.4
#1  0x00007ffff7de74fa in call_init.part () at /lib64/ld-linux-x86-64.so.2
#2  0x00007ffff7de7606 in _dl_init () at /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff7debade in dl_open_worker () at /lib64/ld-linux-x86-64.so.2
#4  0x00007ffff4d19b04 in _dl_catch_error () at /usr/lib/libc.so.6
#5  0x00007ffff7deb2fa in _dl_open () at /lib64/ld-linux-x86-64.so.2
#6  0x00007ffff7bd4e86 in  () at /usr/lib/libdl.so.2
#7  0x00007ffff4d19b04 in _dl_catch_error () at /usr/lib/libc.so.6
#8  0x00007ffff7bd5587 in  () at /usr/lib/libdl.so.2
#9  0x00007ffff7bd4f22 in dlopen () at /usr/lib/libdl.so.2
#10 0x00007fffc3a1452e in g_module_open () at /usr/lib/libgmodule-2.0.so.0
#11 0x00007fffb7b01078 in  () at /usr/lib/libgtk-x11-2.0.so.0
#12 0x00007fffb7b013db in  () at /usr/lib/libgtk-x11-2.0.so.0
#13 0x00007fffb7ae7e28 in  () at /usr/lib/libgtk-x11-2.0.so.0
#14 0x00007fffe90c9e6f in g_option_context_parse ()
    at /usr/lib/libglib-2.0.so.0
#15 0x00007fffb7ae8448 in gtk_parse_args () at /usr/lib/libgtk-x11-2.0.so.0
#16 0x00007fffb7ae84c9 in gtk_init () at /usr/lib/libgtk-x11-2.0.so.0
#17 0x00007fffbc3a32d4 in  ()
    at /usr/lib/qt/plugins/platformthemes/libappmenu-qt5.so
#18 0x00007fffbc3a401e in  ()
    at /usr/lib/qt/plugins/platformthemes/libappmenu-qt5.so
#19 0x00007ffff66967dd in QPlatformThemeFactory::create(QString const&, QString

**Comment by MartinBriza** [comment]
You have to rebuild it on every Qt update, otherwise it's not possible to load the plugin dynamically. I guess that's the problem in your case.
